MCNMedia/Controllers/RecordingReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MCNMedia_Dev.Models;
using MCNMedia_Dev.Repository;
using Microsoft.AspNetCore.Mvc;

namespace MCNMedia_Dev.Controllers
{
    public class RecordingReportController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        DashBoardClientDataAccessLayer clientdashboardData = new DashBoardClientDataAccessLayer();

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RecordingReportList()
        {
            try
            {
                GenericModel gm = new GenericModel();

                ViewBag.SchDate = DateTime.Now.ToString("dd-MMM-yyyy");

                DateTime date = DateTime.Now;
                gm.LDashBoardClients = clientdashboardData.GetRecordingReport(-1, date);
                return View(gm);


            }
            catch (Exception e)
            {
                ShowMessage("Dashboard Error" + e.Message);

                throw;
            }
        }

        public IActionResult Search(DateTime eventDate)
        {
            try
            {

                ViewBag.SchDate = eventDate.ToString("dd-MMM-yyyy");
                GenericModel gm = new GenericModel();
                //DateTime date = genericModel.DashBoardClients.ScheduleEventDate;
                gm.LDashBoardClients = clientdashboardData.GetRecordingReport(-1, eventDate);
                return View("/Views/RecordingReport/RecordingReportList.cshtml", gm);
            }
            catch (Exception e)
            {
                ShowMessage("Search Church  Error" + e.Message);
                throw;
            }
        }

        private void ShowMessage(string exceptionMessage)
        {
            log.Info("Exception: " + exceptionMessage);
        }
    }
}

MCNMedia/Views/RecordingReport/RecordingReportList.cshtml
@model MCNMedia_Dev.Models.GenericModel
@{ ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml"; }
<!-- partial:partials/_horizontal-navbar.html -->
<!-- partial -->
<div class="row ">
    <div class="col-12">
        <!--Today Schedules Start-->
        @*<div class="col-md-6 grid-margin">*@
        <div class="card">
            <div class="card-header card-header-custom">
                Recording Report
            </div>
            <div class="card-body">
                <form method="post" asp-action="Search" asp-controller="RecordingReport">
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Date</label>
                        <div class="col-sm-4">
                            <div id="datepicker" class="input-group date datepicker">
                                <input type="text" id="SetSearchDate" name="eventDate" class="form-control" placeholder="Event Date" />
                                <span class="input-group-addon input-group-append border-left">
                                    <span class="ti-calendar input-group-text"></span>
                                </span>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <button type="submit" class="btn btn-primary btn-sm text-white pull-right" title="Search"><i class="mdi mdi-table-search text-white"></i>Search</button>
                        </div>
                    </div>
                </form>
                <div class="table-responsive">
                    <table class="table table-striped table-borderless">
                        <thead>
                            <tr>
                                <th class="text-wrap">Church</th>
                                <th class="text-wrap">Event Name</th>
                                <th class="text-wrap">Event Status</th>
                                <th class="text-wrap">Event Time</th>
                                <th class="text-wrap">Start/Stop</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.LDashBoardClients)
                             {
                                <tr>
                                    <td class="text-wrap">
                                        @Html.DisplayFor(modelItem => item.ChurchName, new { @class = "text-wrap" })
                                    </td>
                                    <td class="text-wrap">
                                        @Html.DisplayFor(modelItem => item.ScheduleEventName, new { @class = "text-wrap" })
                                    </td>
                                    @if (item.ScheduleStatus == "Pending")
                                    {
                                        <td class="font-weight-medium text-danger">
                                            @Html.DisplayFor(modelItem => item.ScheduleStatus, new { @class = "text-wrap" })
                                        </td> 
                                    }
                                    else if (item.ScheduleStatus == "In Progress")
                                    {
                                        <td class="font-weight-medium text-warning">
                                            @Html.DisplayFor(modelItem => item.ScheduleStatus, new { @class = "text-wrap" })
                                        </td> 
                                    }
                                    else if (item.ScheduleStatus == "Completed")
                                    {
                                        <td class="font-weight-medium text-info">
                                            @Html.DisplayFor(modelItem => item.ScheduleStatus, new { @class = "text-wrap" })
                                        </td> 
                                    }
                                    else if (item.ScheduleStatus == "Published")
                                    {
                                        <td class="font-weight-medium text-success">
                                            @Html.DisplayFor(modelItem => item.ScheduleStatus, new { @class = "text-wrap" })
                                        </td>
                                    }
                                    else if (item.ScheduleStatus == "Waiting")
                                    {
                                        <td class="font-weight-medium text-black">
                                            @Html.DisplayFor(modelItem => item.ScheduleStatus, new { @class = "text-wrap" })
                                        </td> 
                                    }
                                    else
                                    {
                                        <td class="font-weight-medium text-behance">
                                            @Html.DisplayFor(modelItem => item.ScheduleStatus, new { @class = "text-wrap" })
                                        </td>
                                    }
                                    <td class="text-wrap">
                                        @Html.DisplayFor(modelItem => item.ScheduleEventTime, new { @class = "text-wrap" })
                                    </td>
                                    @if (item.ScheduleStatus == "In Progress")
                                     {
                                        <td class="font-weight-medium text-black ">
                                            <button type="submit" onclick="RevokeStopRec(@item.ScheduleId)" class="btn btn-danger btn-sm text-white mb-2" data-toggle="tooltip" data-placement="bottom" title="Stop Rec"><i class="fa fa-stop text-white pr-1"></i>Stop Rec</button>
                                        </td>
                                     }
                                     else if (DateTime.Now > Convert.ToDateTime(item.ScheduleEventTime) && DateTime.Now < Convert.ToDateTime(item.ScheduleEventTime.ToString()).AddMinutes(item.RecordingDuration) && item.ScheduleStatus == "Pending" && item.RecordingDuration != 0)
                                     {
                                        <td class="font-weight-medium text-black ">
                                            <button type="submit" onclick="RevokeStartRec(@item.ScheduleId)" class="btn btn-success btn-sm text-white mb-2" data-toggle="tooltip" data-placement="bottom" title="StartRec"><i class="fa fa-play-circle text-white pr-1"></i>Start Rec</button>
                                        </td>
                                     }
                                     else
                                     {
                                        <td class="font-weight-medium text-black ">
                                        </td>
                                     }
                                </tr>
                             }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!--Today Schedules End-->
</div>

@*</div>*@

<script type="text/javascript">

    $(document).ready(function () {
        var date = '@ViewBag.SchDate';
        $('#SetSearchDate').val(date);
    })

    function RevokeStartRec(scheduleId) {
        var formData = new FormData();
        formData.append("scheduleId", scheduleId);
        $.ajax({
            type: "POST",
            url: "/Schedule/StartRecordingSchedule/",
            data: formData,
            processData: false,  // tell jQuery not to process the data
            contentType: false,  // tell jQuery not to set contentType
            success: function (result) {
                location.reload();
            },
            error: function (errormessage) {
                //alert(errormessage.responseText);
            }
        });
    }

    function RevokeStopRec(scheduleId) {
        var formData = new FormData();
        formData.append("scheduleId", scheduleId);
        $.ajax({
            type: "POST",
            url: "/Schedule/StopRecordingSchedule/",
            data: formData,
            processData: false,  // tell jQuery not to process the data
            contentType: false,  // tell jQuery not to set contentType
            success: function (result) {
                location.reload();
            },
            error: function (errormessage) {
                //alert(errormessage.responseText);
            }
        });
    }
</script>