MCNMedia/Models/Camera.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MCNMedia_Dev.Models
{
    public class Camera
    {
        public int CameraId { get; set; }
        public string CameraName { get; set; }
        public string CameraUrl { get; set; }
        public string RtspPort { get; set; }
        public string HttpPort { get; set; }
        public string CameraSlug { get; set; }
        public _Helper.CameraType CameraType { get; set; }
        public bool IsCameraLive { get; set; }
        public bool IsCameraStreaming { get; internal set; }
        public string StreamingProtocol { get; set; }
        public string LiveStreamUrl { get; internal set; }
        public Boolean CameraScheduleIsRepeated { get; set; }
        public string App { get; set; }
        public string CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public string UpdatedAt { get; set; }
        public int UpdatedBy { get; set; }

        public int ChurchId { get; set; }
        public string ChurchName { get; set; }
        public string ChurchUniqueIdentifier { get; internal set; }
    
        public int ServerId { get; set; }
        public string ServerName { get; set; }
        public string ServerIP { get; set; }
        public string ServerPort { get; set; }
        public string ServerUser { get; set; }
        public string ServerPassword { get; set; }
    }
} 

MCNMedia/Models/ChurchLock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MCNMedia_Dev.Models
{
    public class ChurchLock
    {
        public string Password { get; set; }
        //for the locked churches
        public string Slug { get; set; }
        public int churchPass { get; set; }

        public int ChurchId { get; set; }

        public string ChurchName { get; set; }
    }
}

MCNMedia/Models/Profile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MCNMedia_Dev.Models
{
    public class Profile
    {
        public Church Churches { get; set; }
        //public Camera Cameras { get; set; }
        //public MediaChurch Media { get; set; }
        //public Schedule Schedules { get; set; }
        //public Recording Recordings { get; set; }
        public Announcement Announcement { get; set; }
        public NewsLetter newsletter { get; set; }
        public Notice notice { get; set; }

        public  ChurchDonation churchDonation { get; set; }

        // Lists
        public IEnumerable<Church> ChurchList { get; set; }
        public List<WebsiteMedia> mediaList { get; set; }
        public IEnumerable<Camera> CameraList { get; set; }
        public IEnumerable<MediaChurch> VideoList { get; set; }
        public IEnumerable<MediaChurch> SlideshowList { get; set; }
        public IEnumerable<MediaChurch> PictureList { get; set; }
        public IEnumerable<NewsLetter> ChurchNewsLetterList { get; set; }
        public IEnumerable<Schedule> ScheduleList { get; set; }
        public IEnumerable<Recording> RecordingList { get; set; }
        public MediaChurch mediaChurch { get; set; }
        public List<MediaChurch> MediaChurchList { get; set; }
        public IEnumerable<Notice> NoticeList { get; set; }
        public IEnumerable<Schedule> NowScheduleList { get; set; }
        public IEnumerable<Schedule> NextScheduleList { get; set; }
        public Schedule NextSchedule { get; set; }
        public IEnumerable<Schedule> ScheduleListDay0 { get; set; }
        public IEnumerable<Schedule> ScheduleListDay1 { get; set; }
        public IEnumerable<Schedule> ScheduleListDay2 { get; set; }
        public IEnumerable<Schedule> ScheduleListDay3 { get; set; }
        public IEnumerable<Schedule> ScheduleListDay4 { get; set; }
        public IEnumerable<Schedule> ScheduleListDay5 { get; set; }
        public IEnumerable<Schedule> ScheduleListDay6 { get; set; }
        public IEnumerable<Schedule> UpcomingSchedule { get; set; }
    }
}

MCNMedia/Models/RecordingLock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MCNMedia_Dev.Models
{
    public class RecordingLock
    {
        public String Password { get; set; }
        public int RecordingPass { get; set; }
    }
}

MCNMedia/Models/Schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MCNMedia_Dev.Models
{
    public class Schedule
    {
        public int ScheduleId { get; set; }
        public int ChurchId { get; set; }
        public string ChurchName { get; set; }
        public string Slug { get; set; }
        public string Town { get; set; }

        [Required]
        public string EventName { get; set; }
        //[DisplayFormat(DataFormatString = "{0:yyyy/MMM/dd}")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime EventDate { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:ddd}")]
        public string EventDay { get; set; }
        [EnumDataType(typeof(DayOfWeek))]
        public EventDay Days { get; set; }
        //  [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm}")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
        public DateTime EventTime { get; set; }

        public int RecordDuration { get; set; }
 

        public int CameraId  { get; set; }
        public string CameraName { get; set; }
        public string Password { get; set; }

        public Boolean Record  {get; set;}
        public Boolean IsRepeated { get; set; }
        public int UpdatedBy { get; set; }
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MMM-yyyy}/{0:hh:mm tt}")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int CreatedBy { get; set; }

    }
    public enum EventDay
    {

        [Description("Monday")]
        Monday,
        [Description("Tuesday")]
        Tuesday,
        [Description("Wednesday")]
        Wednesday,
        [Description("Thursday")]
        Thursday,
        [Description("Friday")]
        Friday,
        [Description("Saturday")]
        Saturday,
        [Description("Sunday")]
        Sunday
        
    }
}

MCNMedia/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MCNMedia_Dev.Models;

namespace MCNMedia_Dev.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Home()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MCNMedia/Controllers/WebsiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MaxMind.GeoIP2;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using MCNMedia_Dev._Helper;
using MCNMedia_Dev.Models;
using Microsoft.AspNetCore.Hosting;
using MCNMedia_Dev.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static MCNMedia_Dev.Models.Church;
using System.IO;
using Microsoft.AspNetCore.Diagnostics;
using MaxMind.GeoIP2.Model;
using Microsoft.AspNetCore.Http.Extensions;
using DNTCaptcha.Core;
using Microsoft.Extensions.Options;
using System.Web;

namespace MCNMedia_Dev.Controllers
{
    public class WebsiteController : Controller
    {
        
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IDNTCaptchaValidatorService _validatorService;
        private readonly DNTCaptchaOptions _captchaOptions;

        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        ScheduleDataAccessLayer _scheduleDataAccessLayer = new ScheduleDataAccessLayer();
        ChurchDataAccessLayer _churchDataAccessLayer = new ChurchDataAccessLayer();
        RecordingDataAccessLayer _recordDataAccess = new RecordingDataAccessLayer();
        WebsiteDataAccessLayer _websiteDataAccessLayer = new WebsiteDataAccessLayer();
        //SubscriptionDataAccessLayer subDataAccess = new SubscriptionDataAccessLayer();
        PlaceAccessLayer _placeAccessLayer = new PlaceAccessLayer();
        TestinomialDataAccessLayer testinomialDataAccess = new TestinomialDataAccessLayer();
        ChurchDonationDataAccessLayer churchDonationDataAccessLayes = new ChurchDonationDataAccessLayer();
        GenericModel gm = new GenericModel();
        Website website1 = new Website();
        //CookieOptions cookieOptions = new CookieOptions();
        public WebsiteController(IHostingEnvironment hostingEnvironment, IDNTCaptchaValidatorService validatorService, IOptions<DNTCaptchaOptions> captchaOptions)
        {
            _hostingEnvironment = hostingEnvironment;
            _validatorService = validatorService;
            _captchaOptions = captchaOptions==null?throw new ArgumentNullException(nameof(captchaOptions)):captchaOptions.Value;
        }
        public IActionResult index()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult ContactUs(Website web)

        {
            try
            {
                //if (!_validatorService.HasRequestValidCaptchaEntry(Language.English, DisplayMode.ShowDigits))
                //{
                //    ViewBag.ErrorMsg = "InValid Captcha Kindly Provide a valid Captcha";
                //    return View(web);
                //}

                bool containsHTML = (web.ContactName != HttpUtility.HtmlEncode(web.ContactName));
                bool containsHTML2 = (web.ContactEmail != HttpUtility.HtmlEncode(web.ContactEmail));
                bool containsHTML3 = (web.ContactSubject != HttpUtility.HtmlEncode(web.ContactSubject));
                bool containsHTML4 = (web.Message != HttpUtility.HtmlEncode(web.Message));
                if (containsHTML || containsHTML2 || containsHTML3 || containsHTML4)
                {
                    throw new Exception("Data is invalid kindly provide a valid data");

                }
                else
                {
                    EmailHelper em = new EmailHelper();
                    _websiteDataAccessLayer.AddContactForm(web);
                    ModelState.Clear();
                    var bodyemail = web.ContactEmail + "" + web.Message;
                    // From email Address info@mcnmedia.tv hardcoded
                    // to email ADD tech@mcnmedia.tv 
                    // from email add captured on the form will cancatenated with body
                    //em.SendEmail(string fromEmail, string toEmail, string toName, string subject, string body);
                    em.SendEmail("info@mcnmedia.tv", "tech@mcnmedia.tv", web.ContactName, web.ContactSubject, bodyemail);
             
                ViewBag.SuccessMsg = "Email Send Successfully";
                return View();
                }
            }

            catch (Exception exp)
            {

                ViewBag.ErrorMsg = "Error Occurreds! " + exp.Message;
                return View();
            }
        }
        private  void AddLogsToLog4Net(string response)
        {
            log.DebugFormat("Wowza - Response - IsSuccess: {0}", response);
        }
        public IActionResult Home()
        {
            try
            {
                
                HttpContext.Session.SetString("Password", "");
                HttpContext.Session.SetString("UserType", "website");
                gm.ChurchList = _churchDataAccessLayer.GetWebsiteChurch().ToList<Church>();
                gm.LSchedulesInHour = UpComingSchedulesInCommingHour();
                gm.CountryList = _placeAccessLayer.GetCountries();
               //gm.testinomial = testinomialDataAccess.GetTestinomials().ToList<Testinomial>();

                List<SelectListItem> listCoutryDDL = LoadCountryDDL();

                ViewBag.Countries = listCoutryDDL;
                if (listCoutryDDL == null)
                {
                    throw new Exception("Country List is Empty");
                }
              
                return View(gm);
            }

            catch (Exception exp)
            {

                ViewBag.ErrorMsg = "Error Occuhomeerreds! " + exp.Message;
                return View(gm);
            }
        }
       

        private void Exception()
        {
            throw new NotImplementedException();
        }

        public JsonResult RecordingList()
        {
            try
            {
                int churchId = (int)HttpContext.Session.GetInt32("chrId");
                List<Recording> RecordingList = _recordDataAccess.Recording_GetByChurch(churchId).ToList();
                return Json(RecordingList);
            }
            catch (Exception e)
            {
                return Json(-1);
                //return Json(new { redirecturl = "../Views/Website/Error.cshtml" }, System.Web.Mvc.JsonRequestBehavior.AllowGet);
            }
        }

        public IActionResult Schedules()
        {
            GenericSchedule gmSch = new GenericSchedule();
            try
            {
                
                gmSch.TodaySchedule = _scheduleDataAccessLayer.GetSchedule_Today().ToList<Schedule>();
                gmSch.UpcomingSchedule = UpComingSchedules();
                gmSch.CurrentSchedule = Schedules_WhatsOnNow();
       
                return View(gmSch);
            }
            catch (Exception exp)
            {
                AddLogsToLog4Net(exp.Message);
                ViewBag.ErrorMsg = "Error Occurreds! " + exp.Message;
                return View(gmSch);
            }
        }

        private IEnumerable<Schedule> Schedules_WhatsOnNow()
        {
            try
            {
                List<Schedule> schedules = _scheduleDataAccessLayer.GetSchedule_WhatsOnNow().ToList<Schedule>();
                return schedules;
            }
            catch (Exception e)
            {
                ShowMesage("Schedule Whats On Now Errors : " + e.Message);
                throw;
            }
        }

        private IEnumerable<Schedule> UpComingSchedulesForChurch(int churchId)
        {
            try
            {
                List<Schedule> schedules = _scheduleDataAccessLayer.GetSchedule_UpComingByChurch(churchId).ToList<Schedule>();
                return schedules;
            }
            catch (Exception e)
            {
                ShowMesage("UpComing Schedules for Church Error : " + e.Message);
                throw;
            }
        }

        private IEnumerable<Schedule> UpComingSchedules()
        {
            try
            {
                List<Schedule> schedules = _scheduleDataAccessLayer.GetSchedule_UpComing_All().ToList<Schedule>();
                return schedules;
            }
            catch (Exception e)
            {
                ShowMesage("UpComing Schedules Error : " + e.Message);
                throw;
            }
        }
        private IEnumerable<Schedule> UpComingSchedulesInCommingHour()
        {
            try
            {
                List<Schedule> schedules = _scheduleDataAccessLayer.GetSchedule_UpComingHour().ToList<Schedule>();
                return schedules;
            }
            catch (Exception e)
            {
                ShowMesage("UpComing Schedules Error : " + e.Message);
                throw;
            }
        }

        public IActionResult ContactUs()
        {
            try
            {
                return View();
            }
            catch (Exception exp)
            {

                ViewBag.ErrorMsg = "Error Occurreds! " + exp.Message;
                return View();
            }
        }

        public IActionResult Churches()
        {
            List<SelectListItem> listCoutryDDL = new List<SelectListItem>();
            try
            {
                gm.ChurchList = _churchDataAccessLayer.GetByClientTypeChurch(1).ToList();
                gm.CountryList = _placeAccessLayer.GetCountries();
                listCoutryDDL = LoadCountryDDL();

                ViewBag.Countries = listCoutryDDL;
                if (listCoutryDDL == null)
                {
                    throw new Exception("Country List is Empty");
                }
               

MCNMedia/Views/Website/Cameras.cshtml
@model MCNMedia_Dev.Models.GenericModel
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Cameras";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";

}



<div class="bg-blue  pt-3 pb-3" style=" position: sticky; top: 0px; z-index:5">
    <div class="container">
        <div class="row m-0 ">
            <div class="text-white font-36 text-center avantgardece">
                CAMERAS

            </div>
        </div>

    </div>
</div>

<div class="row m-0 mt-5 mb-5">

    <div class="col-1 d-lg-block d-none"></div>


    <div class="col-lg-3 col-md-4 col-sm-6">
        @*<div class="deskContent">
            <div class="border bg-white p-4" style="position: sticky; top: 103px;">

                @foreach (Place country in Model.CountryList)
                {
                    <div class="news-wrap mb-3">
                        <a class="btn btn-pink my-2 my-sm-0 pl-xl-5 pl-4 pr-xl-5 pr-4 text-white font-weight-bolder font-14 mb-2" style="width:100%"
                           href="@Url.Action("Cameras", "Website",new {Country = country.PlaceName.Replace(' ','-')})">
                            @country.PlaceName
                        </a>
                    </div>
                }
            </div>
        </div>*@


        @if (Model.CountryList != null)
        {
            <div class=" MobileContent border bg-white p-4" style="position: sticky; top: 103px;">


                @foreach (Place country in Model.CountryList)
                {
                    <div class="news-wrap mb-3">
                        <a class="btn btn-pink my-2 my-sm-0 pl-xl-5 pl-4 pr-xl-5 pr-4 text-white font-weight-bolder font-14 mb-2" style="width:100%"
                           href="@Url.Action("Cameras", "Website",new {Country = country.PlaceName.Replace(' ','-')})">
                            @country.PlaceName
                        </a>
                    </div>
                }

            </div>
        }




    </div>


    @if (ViewBag.CountyList == 1)
    {
        <div class="col-lg-7">
            <div class="row">
                @if (ViewBag.countryName == null)
                {

                }
                else
                {
                    <div class="card-header card-header-custom text-white font-18 font-weight-bolder" style="width: 100%; background-color:#d9356f">
                        <h3>@ViewBag.countryName </h3>
                    </div>
                }
            </div>
            <div class="row">


                @foreach (Place country in Model.CountyList)
                {
                    <div class="m-2" style="width:30%">
                        <a class="btn bg-blue my-2 my-sm-0 p-3 pl-xl-5 pl-4 pr-xl-5 pr-4 text-white font-weight-bolder font-14 mb-2" style="width:100%"
                           href="@Url.Action("Cameras", "Website",new {County = country.PlaceName.Replace(' ','-')})">
                            @country.PlaceName
                        </a>
                    </div>
                }
            </div>
        </div>
    }

    @if (ViewBag.CountyList == 0)
    {
        <div class="col-lg-7">
            <div class="row">
                @if (ViewBag.countyName == null)
                {

                }
                else
                {

                    <div class="card-header card-header-custom text-white font-18 font-weight-bolder" style="width: 100%;  background-color:#1f4a79">
                        <h3> @ViewBag.countyName</h3>
                    </div>
                }
            </div>
            <div class="row">
                @if (Model.ChurchList.Count() > 0)
                {
                    foreach (Church church in Model.ChurchList)
                    {

                        <div class="col-lg-4 col-md-6 p-1 ">
                            <div class=" rounded-lg bg-light-gray p-1">
                                <a href="@Url.Action("Profile", "Website",new { id = church.Slug  })" title="Preview">
                                    <div class="Mobileimage position-relative darker">
                                        <img src="@church.ImageURl" class="w-100 rounded-lg " alt="@church.ChurchName">
                                    </div>
                                    <div class="avantgardece text-center text-blue font-16 mt-2">@church.ChurchName, @church.Town</div>
                                </a>
                            </div>
                        </div>

                    }
                }
                else if (ViewBag.SearchFilter != null)
                {
                    <div class="container bg-blue">
                        <div class="row m-0 ">
                            <div class="col-sm-12 text-white font-26 text-center pt-2 pb-2 avantgardece">
                                Search Result for: @ViewBag.SearchFilter
                            </div>
                            <div class="col-sm-12 text-white font-26 text-center pt-2  pb-4 avantgardece">
                                Sorry, there doesn't seem to be matching this search
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
    }
   

    

    <div class="col-1 d-lg-block d-none"></div>

</div>
<div class="displayblock bg-blue pt-3 pb-3 " style=" position: sticky; top: 0px; z-index:5">
    <div class="container">


        <div class="row m-0">

            <div class=" col-lg-6 col-md-5 p-2 selectors-3 col-sm-6 ml-auto">
                <div class="input-serch-d position-relative">
                    @*<input list='text_editors' class="empty" placeholder="&#xF002;  Select Country">
                        <i class="far fa-angle-down srch-dopr-icn"></i>*@
                    @if (ViewBag.Countries != null)
                    {
                        <select id="select2" name="countryId" class="select-search" onchange="DoPostBack();" asp-items="@(new SelectList(@ViewBag.Countries, "Value", "Text", Context.Session.GetInt32("countryId")))">
                            <option value="-1" selected>--Select Country--</option>
                        </select>
                    }
                    else
                    {
                        <select id="select2" name="countryId" class="select-search">
                            <option value="-1">--Select Country--</option>
                        </select>
                    }
                </div>
            </div>
            <div class=" col-lg-6 col-md-5 p-2 selectors-3 col-sm-6 mr-auto">
                <div class="input-serch-d position-relative">
                    @*<input list='text_editors2' class="empty" placeholder="&#xF002;  Select State">
                        <i class="far fa-angle-down srch-dopr-icn"></i>*@
                    <select name="County" class="select-search" id="County" onchange="SearchCameraByCounty();">
                        <option value="-1">--Select County--</option>
                    </select>
                </div>
                @* <datalist id="text_editors2">

                    <select multiple size=8>
                        <option value="Atom">Atom</option>
                        <option value="Brackets">Brackets</option>
                        <option value="Notepad ++">Notepad ++</option>
                        <option value="Notepad">Notepad</option>
                        <option value="Sublime Text">Sublime Text</option>
                        <option value="TextEdit">TextEdit</option>
                        <option value="TextMate">TextMate</option>
                        <option value="Wordpad">Wordpad</option>
                    </select>
                    </datalist>*@
            </div>
        </div>

    </div>
</div>

<script>
    $(document).ready(function () {
        $('#select2').val('-1');


        DoPostBack();
   $('#County').val('@Context.Session.GetInt32("CountyID")');
    });
    function DoPostBack() {
        var CountryId = document.getElementById('select2').value;

        $.ajax({
            url: "/WebSite/LoadCountyDDL",
            type: "GET",
            data: { countryId: CountryId },
            contentType: "application/json;charset=utf-8",
            datatype: "json",
            success: function (result) {
                var s = '<option value="-1">--Select County--</option>';
                $.each(result, function (key, item) {
                    s += '<option value="' + item.countyId + '">' + item.placeName + '</option>'
                });
                $("#County").html(s);
                
            },
            error: function (errormessage) {
             
                $('#errorMessage').text(errormessage);
                $('#divErrorMsg').removeAttr('hidden');

                var s = '<option value="-1">--Select County--</option>';

                $("#County").html(s);
                $('#County').val('@ViewBag.CountyID');




            }
        });
    }

    function SearchCameraByCounty() {
        var filter = "";
        var countrySelect = document.getElementById("select2");
        var countryName = countrySelect.options[countrySelect.selectedIndex].text.replace(" ", "-").replace(/\s/g, "-");
        if (countrySelect.value == "-1") {
            filter = "Country=all";
        }
        else {
            filter = "Country=" + countryName;
        }

        var countySelect = document.getElementById("County");
        var countyName = countySelect.options[countySelect.selectedIndex].text;
        if (countySelect.value == "-1") {
            filter += "&County=all";
        }
        else {

            filter += "&County=" + countyName;
        }
        window.location.href = "/Website/Cameras?" + filter;
    }

    $('.cover').on('click', function () {
        $(this).children().css({
            'z-index': 1,
            'opacity': 1
        });
        $(this).children().trigger('play');

    });

    $('video').on('click', function () {
        console.log('a');
    });


</script>

MCNMedia/Views/Website/ChurchLock.cshtml
@using Microsoft.AspNetCore.Http;
@model MCNMedia_Dev.Models.GenericModel
@{
    ViewData["Title"] = "ChurchLock";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";
}


@{
    TempData.Keep("Slug");
    TempData.Keep("ChrName");
}






<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth lock-full-bg">
            <div class="row w-100 justify-content-center">
                <div class="col-lg-8 mx-auto">
                    <div class="auth-form-transparent text-left p-0 text-center">
                        <label class="mb-1 pt-4 font-18 font-weight-bolder text-pink " for="examplePassword1"><p>This Camera has been Password Protected.</p> 
                        <p> Please contact <b> @TempData["ChrName"] </b> for the password for this Camera.</p></label>
                        <Center>
                            <form class="pt-5 col-lg-6  " asp-action="ChurchLock" asp-controller="Website" method="post">
                                <div class="form-group ">



                                    <input type="password" asp-for="churchLock.Password" name="Password" class="form-control text-center" id="examplePassword1" placeholder="Password">
                                </div>
                                <div class="mt-5">
                                    <button type="submit" class="btn btn-block bg-blue text-white btn-lg font-weight-medium" href="@Url.Action("ChurchLock", "Website")">Unlock</button>
                                </div>
                                <br />

                            </form>
                        </Center>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>